---
# Security Variables
enable_pass: "cisco"
enable_secret: "cisco123"
console_pass: "cisco"
vty_pass: "cisco"
banner_text: "Unauthorized Access is Prohibited!"

# Links Subnets (IP Allocation)
# Link R1-R2 (10.12.12.0/24)
ip_r1_to_r2: "10.12.12.1"
ip_r2_to_r1: "10.12.12.2"

# Link R2-R3 (10.23.23.0/24)
ip_r2_to_r3: "10.23.23.2"
ip_r3_to_r2: "10.23.23.3"

# Link R3-R4 (10.34.34.0/24)
ip_r3_to_r4: "10.34.34.3"
ip_r4_to_r3: "10.34.34.4"

subnet_mask: "255.255.255.0"


# OSPF Configuration
ospf_process_id: 1
ospf_area: 0
